_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  MASK_ON: False
  WEIGHTS: "./output/PubLayNet_table/FasterRCNN32x8/052101/model_final.pth"
  PIXEL_STD: [57.375, 57.120, 58.395]
  RESNETS:
    STRIDE_IN_1X1: False  # this is a C2 model
    NUM_GROUPS: 32
    WIDTH_PER_GROUP: 8
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 1
  RETINANET:
    NUM_CLASSES: 1
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
  RPN:
    BATCH_SIZE_PER_IMAGE: 512
DATASETS:
  TRAIN: ("ICDAR2019_train",)
  TEST: ("ICDAR2019_val",)
SOLVER:
  STEPS: (6400,  10000)
  MAX_ITER: 11000
  BASE_LR: 0.01
  GAMMA: 0.1
  WARMUP_FACTOR: 0.3333333333333333
  WARMUP_ITERS: 20
  CHECKPOINT_PERIOD: 6400
  IMS_PER_BATCH: 4
INPUT:
  MIN_SIZE_TRAIN: (400,)
  MAX_SIZE_TRAIN: 512
  MIN_SIZE_TEST: 400
  MAX_SIZE_TEST: 512
TEST:
  AUG:
    FLIP: False
OUTPUT_DIR: "./output/ICDAR2019/FasterRCNN"