# file-from:  faster_rcnn_X_101_32x8d_FPN_3x.yaml
# source: e2e_faster_rcnn_X_101_64x4d_FPN_1x.yaml
# (https://github.com/ibm-aur-nlp/PubLayNet/blob/master/pre-trained-models/Faster-RCNN/e2e_faster_rcnn_X-101-64x4d-FPN_1x.yaml)
# set for PubLayNet: https://github.com/ibm-aur-nlp/PubLayNet
_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  MASK_ON: False
  # WEIGHTS: "detectron2://ImageNetPretrained/FAIR/X-101-32x8d.pkl"
  PIXEL_STD: [57.375, 57.120, 58.395]
  RESNETS:
    STRIDE_IN_1X1: False  # this is a C2 model
    NUM_GROUPS: 64
    WIDTH_PER_GROUP: 4
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 5
  RETINANET:
    NUM_CLASSES: 5
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
  RPN:
    BATCH_SIZE_PER_IMAGE: 512
DATASETS:
  TRAIN: ("medline_train",)
  TEST: ("medline_val",)
SOLVER:
  STEPS: (100000, 126000)
  MAX_ITER: 140000
  BASE_LR: 0.01
  GAMMA: 0.1
  WARMUP_FACTOR: 0.3333333333333333
  WARMUP_ITERS: 1
  CHECKPOINT_PERIOD: 20000
  IMS_PER_BATCH: 8
INPUT:
  MIN_SIZE_TRAIN: (400,)
  MAX_SIZE_TRAIN: 512
  MIN_SIZE_TEST: 400
  MAX_SIZE_TEST: 512
TEST:
  AUG:
    FLIP: False
OUTPUT_DIR: "./output/PubLayNet/FasterRCNN"