_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  MASK_ON: True
#  WEIGHTS: "detectron2://ImageNetPretrained/FAIR/X-101-32x8d.pkl"
  PIXEL_STD: [57.375, 57.120, 58.395]
  RESNETS:
    STRIDE_IN_1X1: False  # this is a C2 model
    NUM_GROUPS: 64
    WIDTH_PER_GROUP: 4
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 1
  RETINANET:
    NUM_CLASSES: 1
  RPN:
    BATCH_SIZE_PER_IMAGE: 512
  ROI_MASK_HEAD:
    NUM_CONV: 4
    POOLER_RESOLUTION: 28
    POOLER_SAMPLING_RATIO: 2
DATASETS:
  TRAIN: ("table_train",)
  TEST: ("table_val",)
SOLVER:
  STEPS: (7600, 10000)
  MAX_ITER: 11200
  BASE_LR: 0.01
  GAMMA: 0.1
  WARMUP_FACTOR: 0.3333333333333333
  WARMUP_ITERS: 15
  CHECKPOINT_PERIOD: 2240
  IMS_PER_BATCH: 8
INPUT:
  MIN_SIZE_TRAIN: (400,)
  MAX_SIZE_TRAIN: 512
  MIN_SIZE_TEST: 400
  MAX_SIZE_TEST: 512
OUTPUT_DIR: "./output/PubLayNet_table/MaskRCNN"
